version: '3.8'
services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: postgres-postgis-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: pisa-dengue-api
    restart: always
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      QUARKUS_DATASOURCE_USERNAME: ${DB_USER}
      QUARKUS_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:8081"

volumes:
  postgres_data: